mars_invasion/src/Entity/Areas.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AreasRepository")
 */
class Areas
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="smallint")
     */
    private $s_col_start;

    /**
     * @ORM\Column(type="smallint")
     */
    private $s_col_end;

    /**
     * @ORM\Column(type="smallint")
     */
    private $s_row_start;

    /**
     * @ORM\Column(type="smallint")
     */
    private $s_row_end;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_safe;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $has_ressources;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ground_type;

    /**
     * @ORM\Column(type="boolean")
     */
    private $has_been_investigated;

    /**
     * @ORM\Column(type="smallint")
     */
    private $risk;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Sectors", inversedBy="areas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sectors;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reports", mappedBy="areas")
     */
    private $reports;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Minerals", mappedBy="areas")
     */
    private $minerals;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    public function __construct()
    {
        $this->reports = new ArrayCollection();
        $this->minerals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSColStart(): ?int
    {
        return $this->s_col_start;
    }

    public function setSColStart(int $s_col_start): self
    {
        $this->s_col_start = $s_col_start;

        return $this;
    }

    public function getSColEnd(): ?int
    {
        return $this->s_col_end;
    }

    public function setSColEnd(int $s_col_end): self
    {
        $this->s_col_end = $s_col_end;

        return $this;
    }

    public function getSRowStart(): ?int
    {
        return $this->s_row_start;
    }

    public function setSRowStart(int $s_row_start): self
    {
        $this->s_row_start = $s_row_start;

        return $this;
    }

    public function getSRowEnd(): ?int
    {
        return $this->s_row_end;
    }

    public function setSRowEnd(int $s_row_end): self
    {
        $this->s_row_end = $s_row_end;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIsSafe(): ?bool
    {
        return $this->is_safe;
    }

    public function setIsSafe(bool $is_safe): self
    {
        $this->is_safe = $is_safe;

        return $this;
    }

    public function getHasRessources(): ?bool
    {
        return $this->has_ressources;
    }

    public function setHasRessources(?bool $has_ressources): self
    {
        $this->has_ressources = $has_ressources;

        return $this;
    }

    public function getGroundType(): ?string
    {
        return $this->ground_type;
    }

    public function setGroundType(?string $ground_type): self
    {
        $this->ground_type = $ground_type;

        return $this;
    }

    public function getHasBeenInvestigated(): ?bool
    {
        return $this->has_been_investigated;
    }

    public function setHasBeenInvestigated(bool $has_been_investigated): self
    {
        $this->has_been_investigated = $has_been_investigated;

        return $this;
    }

    public function getRisk(): ?int
    {
        return $this->risk;
    }

    public function setRisk(int $risk): self
    {
        $this->risk = $risk;

        return $this;
    }

    public function getSectors(): ?Sectors
    {
        return $this->sectors;
    }

    public function setSectors(?Sectors $sectors): self
    {
        $this->sectors = $sectors;

        return $this;
    }

    /**
     * @return Collection|Reports[]
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(Reports $report): self
    {
        if (!$this->reports->contains($report)) {
            $this->reports[] = $report;
            $report->setAreas($this);
        }

        return $this;
    }

    public function removeReport(Reports $report): self
    {
        if ($this->reports->contains($report)) {
            $this->reports->removeElement($report);
            // set the owning side to null (unless already changed)
            if ($report->getAreas() === $this) {
                $report->setAreas(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Minerals[]
     */
    public function getMinerals(): Collection
    {
        return $this->minerals;
    }

    public function addMineral(Minerals $mineral): self
    {
        if (!$this->minerals->contains($mineral)) {
            $this->minerals[] = $mineral;
            $mineral->addArea($this);
        }

        return $this;
    }

    public function removeMineral(Minerals $mineral): self
    {
        if ($this->minerals->contains($mineral)) {
            $this->minerals->removeElement($mineral);
            $mineral->removeArea($this);
        }

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }
}

mars_invasion/src/Form/AreasType.php
<?php

namespace App\Form;

use App\Entity\Areas;
use App\Entity\Sectors;
use App\Entity\Minerals;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType; 

class AreasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('s_col_start',IntegerType::class)
            ->add('s_col_end',IntegerType::class)
            ->add('s_row_start',IntegerType::class)
            ->add('s_row_end',IntegerType::class)
            ->add('name',TextType::class)
            ->add('is_safe', ChoiceType::class, [
                'choices'  => [
                    'Yes' => true,
                    'No' => false,
                ],
            ])
            ->add('has_ressources', ChoiceType::class, [
                'choices'  => [
                    'Yes' => true,
                    'No' => false,
                ],
            ])
            ->add('ground_type',TextType::class)
            ->add('has_been_investigated', ChoiceType::class, [
                'choices'  => [
                    'Yes' => true,
                    'No' => false,
                ],
            ])
            ->add('risk',IntegerType::class)
            ->add('sectors', EntityType::class,[
                'class' => Sectors::class,
                'choice_label' => 'number'
            ])
            ->add('minerals', EntityType::class,[
                'class' => Minerals::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('picture',TextType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Areas::class,
        ]);
    }
}

mars_invasion/src/Controller/AreasController.php
<?php

namespace App\Controller;

use App\Entity\Areas;
use App\Entity\Sectors;
use App\Form\AreasType;
use App\Entity\Minerals;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AreasController extends AbstractController
{
    /**
     * @Route("/areas/add", name="areas_add")
     */
    public function index( Request $request )
    {
        $area= new Areas();
        $manager= $this->getDoctrine()->getManager();
        $form = $this->createForm(AreasType::class, $area);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $manager->persist($area);
            $manager->flush();
            $this->addFlash('success', "A new area has been added.");

        }
        return $this->render('areas/index.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/areas/show/{id}", name="areas_show")
     */
    public function show($id)
    {
    
       // $sectorRepo = $this->getDoctrine()->getRepository(Sectors::class);
       // $sector_targeted= $sectorRepo->find($id);
       // $areasRepo = $this->getDoctrine()->getRepository(Areas::class);
       // $areas_of_sector_targeted = $areasRepo->findBySectors($sector_targeted);


        $sectorRepo = $this->getDoctrine()->getRepository(Sectors::class);
        $areasRepo = $this->getDoctrine()->getRepository(Areas::class);
        $mineralsRepo = $this->getDoctrine()->getRepository(Minerals::class);


        $area= $areasRepo->find($id);
        $sectorOfArea = $area->getSectors()->getId();
        //dd($sectorOfArea);
        $sectorInfo = $sectorRepo->find($sectorOfArea);

        //$area_minerals= $area->getMinerals();
        //dd($area_minerals);
       // dd($area->getMinerals());

       /*$areaMinerals= $area->getMinerals();
        $listOfMineralsEntities = [];
        foreach( $areaMinerals as $mineral){

        $area_minerals= $areasRepo->findByName($mineral);
        $listOfMineralsEntities[] = $area_minerals;

        }
        dd($listOfMineralsEntities);
*/




       /* $areaRepo= $this->getDoctrine()->getRepository(Areas::class);
        $area_selected= $areaRepo->find($id);
        //dd($area_selected);

        $mineralRepo= $this->getDoctrine()->getRepository(Minerals::class);
        $area_selected_minerals= $area_selected->getMinerals();
       // dd($area_selected_minerals);
       // dd($area_selected_minerals['collection']['elements']);

        $mineralEntitiesNeeded= [];
        foreach($area_selected_minerals as $mineral)
        {
            $mineral_searchedBy_name= $mineralRepo->findByName($mineral);
            $mineralEntitiesNeeded[] = $mineral_searchedBy_name;
        }
        //dd($mineralEntitiesNeeded);
        
        return $this->render('areas/show.html.twig', [
            'areas_of_sector_targeted' => $areas_of_sector_targeted ,
            'sector_targeted' => $sector_targeted ,

            'minerals' => $mineralEntitiesNeeded,
            'area' => $area_selected
        ]);


            */
        return $this->render('areas/show.html.twig', [
            'areaInfo' => $area ,
            'sectorInfo' => $sectorInfo 

        ]);
    }
}

mars_invasion/templates/areas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AreasController!{% endblock %}
{% block stylesheets %}
{% endblock %}


{% block body %}
<div class= "container mt-5">
{% for message in app.flashes('success') %}
<div class= "alert alert-success">
{{ message }}
</div>
{% endfor %}
{{form_start(form, {'attr':{'class':'form-row'}}) }}
<div class= "form-group col-md-6">{{ form_row(form.s_col_start, {'label': 'Top corner left value:', 'attr':{'class':'form-control'}}) }}</div>
<div class= "form-group col-md-6">{{ form_row(form.s_col_end,{'label': 'Top corner right value:', 'attr':{'class':'form-control'}}) }} </div>
<div class= "form-group col-md-6 ">{{ form_row(form.s_row_start,{'label': 'Bottom corner left value:', 'attr':{'class':'form-control'}}) }} </div>
<div class= "form-group col-md-6 ">{{ form_row(form.s_row_end,{'label': 'Bottom corner right value:', 'attr':{'class':'form-control'}}) }}</div>
<div class= "form-group col-md-6 ">{{ form_row(form.name,{'label': 'Name:', 'attr':{'class':'form-control'}}) }}</div>
<div class= "form-group col-md-6">{{ form_row(form.is_safe,{'label': 'Is Safe:', 'attr':{'class':'form-control'}}) }} </div>
<div class= "form-group col-md-6 ">{{ form_row(form.has_ressources,{'label': 'Has Ressources:', 'attr':{'class':'form-control'}}) }} </div>
<div class= "form-group col-md-6 ">{{ form_row(form.ground_type,{'label': 'Landscape:', 'attr':{'class':'form-control'}}) }}</div>
<div class= "form-group col-md-6 ">{{ form_row(form.has_been_investigated,{'label': 'Has Been Investigated:', 'attr':{'class':'form-control'}}) }}</div>
<div class= "form-group col-md-6">{{ form_row(form.risk,{'label': 'Risk level:', 'attr':{'class':'form-control'}}) }} </div>
<div class= "form-group col-md-6 ">{{ form_row(form.sectors,{'label': 'Sector associated:', 'attr':{'class':'form-control'}}) }} </div>
<div class= "form-group col-md-6 ">{{ form_row(form.minerals,{'label': 'Dangerous Ores Reported:', 'attr':{'class':'form-control'}}) }}</div>
<div class= "form-group col-md-6 ">{{ form_row(form.picture,{'label': 'Picture:', 'attr':{'class':'form-control'}}) }}</div>

<div class= "form-group col-md-8 "><button class="btn btn-warning p-3 text-white "type=submit>Add to database</button>
{{form_end(form)}}
</div>
</div>

{% endblock %}

mars_invasion/templates/areas/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} <link rel="stylesheet" href="/individualSector.css"> {% endblock %}


{% block body %}
{#<h1> Narrow it down some Here is   You are currently sector {{sector_targeted.number}} rerepsentation</h1> #}
<h2 class='mt-4 ml-4'> You are currently perusing over all the areas pertaining to sector {{sectorInfo.number}}</h2>

<h3 class='ml-4'>To get detailed informations on a particular area, please click on the one you are interested in.</h3> 

<div class="row p-4">
    <div class= "col-md-4">
    <h3>{{ areaInfo.name}} :</h3>
    <ul>
    <li>Marking out of the area: {{ areaInfo.sColStart }} / {{areaInfo.sColEnd}} / {{areaInfo.sRowStart}} / {{areaInfo.sRowEnd}}  </li>
    <li> Investigations carried out: {% if areaInfo.hasBeenInvestigated == 1  %} Area mapped 

    <li> Threat level: {{ areaInfo.risk}}</li>
    <li>Status : {% if areaInfo.isSafe == 0  %} Safe {% else  %} Better stay away {% endif %}</li>
    <li> Riches: {% if areaInfo.hasRessources == 1  %} Ressouces found {% else %} No ressources of any sort found {% endif %}</li>
    <li> GroundType: {{ areaInfo.groundType}}</li>
     <li> Minerals:  {% for mineral in areaInfo.minerals %} {{mineral.name}} {% endfor %}</li> 

    {% else %} Area as yet to be mapped {% endif %}</li>
   </ul>
   <p>Please help us gathering more information on the area</p>
   {% if not app.user %} 
    <a class='btn btn-warning' href="{{ path('login')}}">You can't send a report unless you are logged in. </a>
{% else %}
   <a class='btn btn-warning' href="{{ path('report_create', {'id': areaInfo.id})}}"> Send a report  </a>
{% endif %}


    </div>

    <div class="sectorCartography col-md-8" >
        {% for area in sectorInfo.areas %}                                                        
            <a class='areaLink d-flex justify-content-center align-items-center' data-id={{ area.id }} style='grid-column-start:{{area.sColStart}};grid-column-end:{{area.sColEnd}};grid-row-start:{{area.sRowStart}};grid-row-end:{{area.sRowEnd}};background-image:url({{ area.picture }}); background-size:cover' href="{{path('areas_show', {'id': area.id} )}}"><div style="background: rgba(0,0,0,0.8); padding:1em; color:white" >{{ area.name }}</div></a>
        {% endfor %}
    
    </div>
</div>
{% endblock %}
{% block javascripts %}<script src="/areaInfo.js"></script>{% endblock %}