mars_invasion/src/Entity/Minerals.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MineralsRepository")
 */
class Minerals
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $effects_on_population;

    /**
     * @ORM\Column(type="smallint")
     */
    private $threat_evaluation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $icon;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Areas", inversedBy="minerals")
     */
    private $areas;

    public function __construct()
    {
        $this->areas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEffectsOnPopulation(): ?string
    {
        return $this->effects_on_population;
    }

    public function setEffectsOnPopulation(string $effects_on_population): self
    {
        $this->effects_on_population = $effects_on_population;

        return $this;
    }

    public function getThreatEvaluation(): ?int
    {
        return $this->threat_evaluation;
    }

    public function setThreatEvaluation(int $threat_evaluation): self
    {
        $this->threat_evaluation = $threat_evaluation;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(?string $icon): self
    {
        $this->icon = $icon;

        return $this;
    }

    /**
     * @return Collection|Areas[]
     */
    public function getAreas(): Collection
    {
        return $this->areas;
    }

    public function addArea(Areas $area): self
    {
        if (!$this->areas->contains($area)) {
            $this->areas[] = $area;
        }

        return $this;
    }

    public function removeArea(Areas $area): self
    {
        if ($this->areas->contains($area)) {
            $this->areas->removeElement($area);
        }

        return $this;
    }
}

mars_invasion/src/Form/MineralsType.php
<?php

namespace App\Form;

use App\Entity\Areas;
use App\Entity\Minerals;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MineralsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class)
            ->add('effects_on_population',TextareaType::class)
            ->add('threat_evaluation',IntegerType::class)
            ->add('icon',TextType::class)
            ->add('areas', EntityType::class,[
                'class' => Areas::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Minerals::class,
        ]);
    }
}

mars_invasion/src/Controller/MineralsController.php
<?php

namespace App\Controller;

use App\Entity\Minerals;
use App\Form\MineralsType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MineralsController extends AbstractController
{
     /**
     * @Route("/minerals/list", name="list_minerals")
     */
    public function index( Request $request)
    {
        $mineralsRepo= $this->getDoctrine()->getRepository(Minerals::class);
        $minerals= $mineralsRepo->findall();
       // dd($minerals);

        return $this->render('minerals/minerals.html.twig', [
            'minerals' => $minerals
        ]);
    }

    /**
     * @Route("/minerals/add", name="minerals_add")
     */
    public function add( Request $request)
    {
        $mineral= new Minerals();
        $manager= $this->getDoctrine()->getManager();
        $form = $this->createForm(MineralsType::class, $mineral);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $manager->persist($mineral);
            $manager->flush();
            $this->addFlash('success', 'Your discovery has been registered.');


            return $this->redirectToRoute('list_minerals');
        }
        return $this->render('minerals/index.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

mars_invasion/templates/minerals/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MINERALsController!{% endblock %}
{% block stylesheets %}
{% endblock %}

 
{% block body %}
<div class= "container mt-5">
{% for message in app.flashes('success') %}
<div class= "alert alert-success">
{{ message }}
</div>
{% endfor %}
{{form_start(form, {'attr':{'class':'form-row'}}) }}
<div class= "form-group col-md-6">{{ form_row(form.name, {'label': 'Ore name:', 'attr':{'class':'form-control'}}) }}</div>
<div class= "form-group col-md-6">{{ form_row(form.effects_on_population,{'label': 'Effects:', 'attr':{'class':'form-control'}}) }} </div>
<div class= "form-group col-md-6 ">{{ form_row(form.threat_evaluation,{'label': 'Threat level:', 'attr':{'class':'form-control'}}) }} </div>
<div class= "form-group col-md-6 ">{{ form_row(form.icon,{'label': 'Picture:', 'attr':{'class':'form-control'}}) }}</div>
<div class= "form-group col-md-6 ">{{ form_row(form.areas,{'label': 'Spotted in area:', 'attr':{'class':'form-control'}}) }}</div>
<div class= "form-group col-md-6 "><img style="width: 520px; height:240px"src="/ore.jpg"></div>
<div class= "form-group col-md-8 "><button class="btn btn-warning p-3 text-white "type=submit>Add to database</button>
{{form_end(form)}}
</div>

</div>

{% endblock %}

mars_invasion/templates/minerals/minerals.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MINERALsController!{% endblock %}
{% block stylesheets %}
{% endblock %}


{% block body %}
<div class=container>
<h1 class='pt-4'>List of all dangerous minerals known to earthlings</h1>
<h3>A new discovery to report ? <a href="{{path('minerals_add')}}">Fill in the form</a></h3>

<div class="row row-cols-1 row-cols-md-3">
  

{% for mineral in minerals %}
<div class="col mb-4">
  <div class="card">
    <img src="{{mineral.icon}}" style="height:250px; "class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Designation:{{mineral.name}}</h5>
      <p class="card-text">Known effects on population:{{mineral.effectsOnPopulation}} </p>
      <p class="card-text">Risk level:{{mineral.threatEvaluation}} </p>
      <p class="card-text"><small class="text-muted">Spotted in areas : {% for mineral in mineral.areas %} {{mineral.name}} {% endfor %}</small></p>
    </div>
  </div>
</div>
{% endfor %}
</div>

</div>

{% endblock %}